[tool.poetry]
name = "exploit-town-tourist-info"
version = "0.1.0"
description = ""
authors = ["Valentin Zahnd <valentin.zahnd@secuteer.com>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.0"
gunicorn = "^21.2.0"
python-magic = "^0.4.27"
flask-httpauth = "^4.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
